### ISSUE TITLE
How to add configurations?

### ISSUE THREAD

**Issue by sunnixx** [mdsecactivebreach/o365-attack-toolkit#1]
Hi 
I am just trying to test this tool out. I've never used GO-Lang so I am not sure where does this configuration part goes, as defined in the README. 

Any help would be appreciated.

**Comment by 0x09AL** [comment]
Hi @sunnixx 
The configuration for the toolkit can be changed on the template.conf.
Please refer to the blogpost for more information : [https://www.mdsec.co.uk/2019/07/introducing-the-office-365-attack-toolkit/](https://www.mdsec.co.uk/2019/07/introducing-the-office-365-attack-toolkit/)
