### ISSUE TITLE
Start server using HTTPS

### ISSUE THREAD

**Issue by groth17** [mdsecactivebreach/o365-attack-toolkit#10]
Is it possible to start the external server using https, I've seen the configuration in http.go and uncommented it and recomplied, but cannot get a TLS server running.. What am I missing.. Any help appreciated..

**Comment by groth17** [comment]
So I eventually worked it out. Certificate files need to be in .pem format.  The Template file shows .crt & .key files which implies they are plain text format, might be worth changing the template.conf.

**Comment by mhomden** [comment]
Hi @0x09AL  - Great tool for training purposes - How can I get the http server to listen on port 443 for the https connection, I can set any other port, it seem that just 443 won't work(?)

**Comment by 0x09AL** [comment]
Hi,
You can change the port on the configuration file. If only port 443 is not working, it means you probably have another service running at that port.

**Comment by mhomden** [comment]
> Hi,
> You can change the port on the configuration file. If only port 443 is not working, it means you probably have another service running at that port.

I did think that - but couldn't see a service running or port open - I'll double check though... thanks

**Comment by mhomden** [comment]
@0x09AL - Double checked - nothing running on port 443, when run the output say running on port 443, but it's not. I did have to modify the http.go file to enable https, but I'm wondering does it work for you?

**Comment by 0x09AL** [comment]
Ah sorry,
If you check the source code the https server is commented out as I wanted to avoid people exposing the interface directly for security reasons.
Please refer to our blogpost for the proper infrastructure implementation.

**Comment by mhomden** [comment]
> Ah sorry,
> If you check the source code the https server is commented out as I wanted to avoid people exposing the interface directly for security reasons.
> Please refer to our blogpost for the proper infrastructure implementation.

So I can start the TLS Server on any other port, just not 443 - still looking into it

**Comment by mhomden** [comment]
@0x09AL cannot start the https server on port 444 or 500 as an example, however I can start it on other ports such as 8443 and 5000 - any thoughts?

**Comment by 0x09AL** [comment]
The new version has been released, closing this issue.
