### ISSUE TITLE
Error when attempting to navigate to management page.

### ISSUE THREAD

**Issue by KRMaxM** [mdsecactivebreach/o365-attack-toolkit#12]
This issue is being faced on a new install. I can fix the issue by running the sql commands on the db file. it will fix the issue but I think there is something affecting db read and write. 

Go Lang Ver: Tried 1.13.1 & 1.14.6

Error: 
2020/07/17 09:44:48 Error : no such table: users
2020/07/17 09:44:48 http: panic serving 127.0.0.1:41396: runtime error: invalid memory address or nil pointer dereference
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc000160000)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x907c80, 0xefe050)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
database/sql.(*Rows).Next(0x0, 0x1)
	/usr/local/go/src/database/sql/sql.go:2744 +0x30
o365-attack-toolkit/database.GetUsers(0xc000166080, 0x2, 0x2)
	/home/max/go/src/o365-attack-toolkit/database/users.go:21 +0xfb
o365-attack-toolkit/server.GetUsers(0xa30c20, 0xc000188000, 0xc00017c200)
	/home/max/go/src/o365-attack-toolkit/server/handlers.go:45 +0x74
net/http.HandlerFunc.ServeHTTP(0x9ab430, 0xa30c20, 0xc000188000, 0xc00017c200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
o365-attack-toolkit/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000f00c0, 0xa30c20, 0xc000188000, 0xc00017c000)
	/home/max/go/src/o365-attack-toolkit/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
net/http.serverHandler.ServeHTTP(0xc0001041c0, 0xa30c20, 0xc000188000, 0xc00017c000)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000160000, 0xa319a0, 0xc000168000)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e

**Comment by katatafish5** [comment]
Just experienced the same issue here.
@KRMaxM - Did you say you had a workaround?

**Comment by KRMaxM** [comment]
> Just experienced the same issue here.
> @KRMaxM - Did you say you had a workaround?

I used sqlitebrowser and the .sql file to execute the query manually. This allowed me to get to the management interface, but testing the tool it does not capture/receive the token after a user logs in.

**Comment by katatafish5** [comment]
@KRMaxM - Cheers thanks.

**Comment by 0x09AL** [comment]
Hi both,
I'm currently working on an improved version of the tool and will probably publish it soon.
Thanks,
Rio

**Comment by CanIPhish** [comment]
Hi, any update on this? I'm very keen to demo this to my colleagues - especially considering the recent SANS breach which seemed to utilise an identical technique. Although I can't seem to get the management page working (same error as the listed issue).

Any assistance would be greatly appreciated. I have the app auth working fine.

Edit 1: Fixed management interface, now tokens aren't getting saved. Will try to fix

Edit 2: Now have token insertion working although it seems like the OAuth process is broken. Going to need input from the project owner

Edit 3: OAuth process is now fixed. Needed code changes in the project as with Edits 1 & 2. Now the OAuth token won't save lol. Onto more fixing!

Edit 4: All fixed. Great tool, thanks!

**Comment by katatafish5** [comment]
@Rices - Were the fixes you mentioned updated in the repository?

**Comment by CanIPhish** [comment]
Nope. Based off what was missing I'm half convinced the coding issues were deliberate. I have a good portion of the project working but some of it still needs fixing (I got working what I needed and left it at that).

I'll rattle through a few:
template.conf file needs an [oauth] identifier e.g. after backdoor

[backdoor]
enabled = true ; Enable/Disable this feature
macro = "C:\\Test.bas" ; The location of the macro file to use for backdooring documents

[oauth]
clientid = xxxxxxxxxxxxxxxxxxxxxxxxxxx
redirecturi = http://localhost:30662/

static/index.html sendAccessToken function should point to /gettoken not /token

under GetToken in http.go I just commented out and rejigged a bunch of the code as whatever it was doing wasn't functioning - see below:
func GetToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	r.ParseForm()
	log.Println(r.FormValue("token"))
	go api.InitializeProfile(r.FormValue("token"), "")
	w.Write([]byte("{\"status\":\"OK\"}"))
	//jsonData := api.GetAllTokens(r.FormValue("token"))
	//log.Println(jsonData)
	//if jsonData != nil {
		//authResponse := model.AuthResponse{}
		//log.Println(jsonData)
		//json.Unmarshal(jsonData, &authResponse)
		//log.Println("Authentication Successful")
		//log.Println("AccessToken")
		//log.Println(authResponse.AccessToken)
		//log.Println("RefreshToken")
		//log.Println(authResponse.RefreshToken)
		//go api.InitializeProfile(authResponse.AccessToken, authResponse.RefreshToken)
		// Do the redirect here
		//w.Write([]byte("{\"status\":\"OK\"}"))
	//}
}

I think those were the main changes. I'm not that familiar with Go as a programming language so you may do better than me here.

**Comment by cyb3r5t4lk3r** [comment]
Hi, @Rices can you help me with configuration? I was trying all recommendations from you, but the tool is not working correctly. The external portal is available, app registration to victim tenant is OK, but I can't save a token and I can't save victim to the database. I debug this problem and my browser returns me 404 error in /gettoken request and the browser wants to send this request to my server.

i use Ubuntu Server 18.04

DEP version is 
version     : devel
build date  :
git hash    :
go version  : go1.8.3
go compiler : gc
platform    : linux/amd64

and Go version is 
go version go1.10.4 linux/amd64
