### ISSUE TITLE
Two issues: Signing In and the Same error with the Management Interface

### ISSUE THREAD

**Issue by helloitsliam** [mdsecactivebreach/o365-attack-toolkit#13]
**Signing In:** When I click the **Sign In** button at http://localhost:30662 I get the following error:

AADSTS7000112: Application '035da677-152b-4a06-a66d-2a5e749b3c69'(Testing for App) is disabled.

I have tried it within two different tenants and same error. 

Management Interface: Same error as this; https://github.com/mdsecactivebreach/o365-attack-toolkit/issues/12
What is the fix?

Thanks

**Comment by helloitsliam** [comment]
Fixed the Management issue, opened the DB, and then execute the SQL, all good on that one. 

Ignore me....Silly me not reading it properly!! My apologies!!!!! Blame it on lack of sleep :-)

Now get the same error listed in issue https://github.com/mdsecactivebreach/o365-attack-toolkit/issues/12, where it does not log anything after authorization. Any thoughts? Thanks

**Comment by KRMaxM** [comment]
@helloitsliam  Are you using chrome in-private browser? 

Open up developer console, do you get an errors?

**Comment by helloitsliam** [comment]
Thanks @KRMaxM I am not. I am using Firefox on Ubuntu Desktop for it. Let me check for errors. I am trying to use it locally for the request and not use full DNS name. So right now my Azure App redirect is localhost, which responds. When I click sign-in it opens then closes, as I have already consented. The only error I get is "404 page not found" which references the localhost. It writes this error from this:

    function sendAccessToken(token){
        var xhr = new XMLHttpRequest();
        xhr.open('POST', '/token', true);
        xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
        xhr.onload = function () {
            **console.log(this.responseText);**
        };
        xhr.send('token='+token);
    }

I am assuming I need to actually use a real DNS that routes correctly?

Update: Just tested using ngrok and still get the same error. 

Thanks

**Comment by 0x09AL** [comment]
Closing as the new version has been released.
