### ISSUE TITLE
Internal server IP

### ISSUE THREAD

**Issue by Meatballs1** [mdsecactivebreach/o365-attack-toolkit#2]
Internal server IP reports as:

```
2019/08/01 12:09:03 Loaded 1 rules successfully.
2019/08/01 12:09:03 Starting Internal Server on 0.0.0.0:8080 
2019/08/01 12:09:03 Starting External Server on 0.0.0.0:30662 
```
but is actually hard-coded to 127.0.0.1.

Would suggest that two configuration options for internal/external are within the template.conf file.

**Comment by 0x09AL** [comment]
Thanks for the info @Meatballs1.
Commit [https://github.com/mdsecactivebreach/o365-attack-toolkit/commit/71e436c1b1325dc10575bc5ddbca315892066640](https://github.com/mdsecactivebreach/o365-attack-toolkit/commit/71e436c1b1325dc10575bc5ddbca315892066640) should fix the issue.
