### ISSUE TITLE
External site hosted on /

### ISSUE THREAD

**Issue by Meatballs1** [mdsecactivebreach/o365-attack-toolkit#3]
The external site is hosted on `/` which means any web crawler is going to hit the signin page. 

Its surprisingly painful to reverse proxy a vanity URL infront of it because any requests to `127.0.0.1:30662/index.html` get 301 redirected to `./`. 

Trying to add a different route via modifying the `ExtMainPage` function also just caused pain and frustration but Im not familar with the middleware :)

I worked around this by moving `index.html` -> `signin.html`

**Comment by 0x09AL** [comment]
Hey @Meatballs1 , the external site hosts and publishes everything that is in the /static/ directory.
By default index.html is used but you can rename it to whatever you want.
